name: shift_view
description: A shift management and wage calculation app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.8
  csv: ^5.0.1
  pdf: ^3.6.0
  share_plus: ^7.2.1
  file_picker: ^8.0.7
  cupertino_icons: ^1.0.3
  

  universal_html: ^2.2.4
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  video_player: ^2.8.1
  chewie: ^1.7.4
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.7

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/ShiftManagerApp.png


  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true