name: firebase_auth_web
version: 5.8.13

environment:
  sdk: '>=2.12.0 <3.0.0'

description: A patched version of firebase_auth_web for local fixes.

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7 