// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7oLzBL-AR1N2Y1b7cqhUmFuJMnCqIZkc',
    appId: '1:530556523067:web:5aad7c47cca98b3f53c21e',
    messagingSenderId: '530556523067',
    projectId: 'shift-view-app',
    authDomain: 'shift-view-app.firebaseapp.com',
    storageBucket: 'shift-view-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBatHMIbjspRW3-va_jEWKRHae5EoWfFH4',
    appId: '1:530556523067:android:b21940c9406e551453c21e',
    messagingSenderId: '530556523067',
    projectId: 'shift-view-app',
    storageBucket: 'shift-view-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfMRgylK0e58sKuoyuVsiwk1NNP-0Nnik',
    appId: '1:530556523067:ios:ff80a285bffcdc0e53c21e',
    messagingSenderId: '530556523067',
    projectId: 'shift-view-app',
    storageBucket: 'shift-view-app.firebasestorage.app',
    iosBundleId: 'com.samueleskenasy.shiftview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfMRgylK0e58sKuoyuVsiwk1NNP-0Nnik',
    appId: '1:530556523067:ios:cd5fd336280d60b153c21e',
    messagingSenderId: '530556523067',
    projectId: 'shift-view-app',
    storageBucket: 'shift-view-app.firebasestorage.app',
    iosBundleId: 'com.example.shiftView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7oLzBL-AR1N2Y1b7cqhUmFuJMnCqIZkc',
    appId: '1:530556523067:web:cf21f52109f635cd53c21e',
    messagingSenderId: '530556523067',
    projectId: 'shift-view-app',
    authDomain: 'shift-view-app.firebaseapp.com',
    storageBucket: 'shift-view-app.firebasestorage.app',
  );

}